### ISSUE TITLE
在连接到pinecone向量数据库时报错，提示"API key is missing, please provide an API key in the header.

### ISSUE THREAD

**Issue by tuihou123321** [cuixiaorui/vue3-ai-assistant#3]
运行： `yarn run ingest`     命令，控制台报错如下： 
---------
```
/usr/local/bin/yarn run ingest
yarn run v1.22.17
$ node script/ingest-data.js
(node:6620) ExperimentalWarning: buffer.File is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///Users/xz/Documents/code/myGithub/vue3-ai-assistant/server/node_modules/langchain/dist/document_loaders/fs/unstructured.js:72
            throw new Error(`Failed to partition file ${this.filePath} with error ${response.status} and message ${await response.text()}`);
                  ^

Error: Failed to partition file /Users/xz/Documents/code/myGithub/vue3-ai-assistant/server/source/vue3-document-en.md with error 401 and message {"detail":"API key is missing, please provide an API key in the header."}
    at UnstructuredLoader._partition (file:///Users/xz/Documents/code/myGithub/vue3-ai-assistant/server/node_modules/langchain/dist/document_loaders/fs/unstructured.js:72:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UnstructuredLoader.load (file:///Users/xz/Documents/code/myGithub/vue3-ai-assistant/server/node_modules/langchain/dist/document_loaders/fs/unstructured.js:81:26)
    at async file:///Users/xz/Documents/code/myGithub/vue3-ai-assistant/server/script/ingest-data.js:17:17

Node.js v18.16.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1
```

## .env文件配置正常

.env配置如下，并且在运行  `yarn run ingest` 命令时 控制台，可以正常打印 process.env.PINECONE_API_KEY 的值。
OPENAI_API_KEY 配置没问题，可以正常使用。请问啥原因

<img width="980" alt="image" src="https://github.com/cuixiaorui/vue3-ai-assistant/assets/7146036/e9c78a02-7374-4509-b0cb-9ddc2fe99a42">
<img width="1501" alt="image" src="https://github.com/cuixiaorui/vue3-ai-assistant/assets/7146036/e17d8a06-657c-4c01-8f42-7cd4355a3855">

<img width="1512" alt="image" src="https://github.com/cuixiaorui/vue3-ai-assistant/assets/7146036/e1e8d10a-c802-4120-aaaa-fd48be55a92f">

**Comment by kiraraty** [comment]
UnstructuredLoader的问题
